name: portfolio
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  slang: ^4.9.1
  get_it: ^8.2.0
  logger: ^2.6.2
  injectable: ^2.5.2
  auto_route: ^10.2.0
  flutter_gen: ^5.12.0
  url_launcher: ^6.3.2
  slang_flutter: ^4.9.0
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  web_smooth_scroll: ^2.0.0
  device_info_plus: ^12.1.0
  freezed_annotation: ^3.1.0
  theme_tailor_annotation: ^3.1.1
  assorted_layout_widgets: ^11.0.0
  intl: ^0.20.2
  flutter_svg: ^2.2.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^3.2.3
  build_runner: ^2.9.0
  theme_tailor: ^3.1.1
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  slang_build_runner: ^4.9.0
  flutter_gen_runner: ^5.12.0
  injectable_generator: ^2.9.0
  auto_route_generator: ^10.2.5

flutter_gen:
  output: lib/core/gen
  integrations:
    image: true
    flutter_svg: true
  colors:
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors

flutter:
  uses-material-design: true

  assets:
    - assets/

    - assets/icons/
    - assets/icons/home/
    - assets/icons/email/
    - assets/icons/phone/
    - assets/icons/github/

    - assets/images/

  fonts:
    - family: Nauryz
      fonts:
        - asset: assets/fonts/Nauryz/Nauryz.ttf
          weight: 700
    - family: Awoma
      fonts:
        - asset: assets/fonts/Awoma/Awoma.ttf
          weight: 400
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPro/Light.ttf
          weight: 300
        - asset: assets/fonts/SFPro/LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SFPro/Regular.ttf
          weight: 400
        - asset: assets/fonts/SFPro/RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SFPro/Medium.ttf
          weight: 500
        - asset: assets/fonts/SFPro/MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SFPro/Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFPro/SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SFPro/Bold.ttf
          weight: 700
        - asset: assets/fonts/SFPro/BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SFPro/Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFPro/HeavyItalic.ttf
          weight: 800
          style: italic
